refresh_delay: 500
seperator: "|"
commands: [ 
	"ğŸ”†$(unixtool brightness_percent)%",
	"ğŸ”‹$(cat /sys/class/power_supply/BAT1/capacity)%",
        "$(date +%a) $(date +%b) $(date +%d)", 
        "$(date +%r)",
    ]
